/**
 * Deploy Runbooks — Phase 58 (ServerBuddy)
 *
 * Guided deployment wizards: checkable steps, generated artifacts
 * (scripts, systemd units, Caddyfile) and a quiz gate before "deploy
 * complete". Three tracks mirroring what this very app uses:
 *
 *   - Vercel  (this repo deploys here — the Next.js + Neon path)
 *   - Railway (containers + managed Postgres)
 *   - VPS + Caddy (mirrors the project's own Caddyfile — reverse proxy,
 *     automatic HTTPS)
 */

export type RunbookStep = {
  id: string;
  title: string;
  body: string;
  /** Code/artifact shown in a copyable block (optional). */
  code?: string;
  codeLabel?: string;
  /** Generated artifact written into the Project when the step completes. */
  generates?: { path: string; content: string };
};

export type QuizQuestion = {
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
};

export type Runbook = {
  id: string;
  platform: string;
  emoji: string;
  blurb: string;
  requires: string; // what the learner should have ready
  steps: RunbookStep[];
  quiz: QuizQuestion[];
};

// ---------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------

/** A hardened-ish systemd unit for a Node app. */
export function generateSystemdUnit(opts: {
  appName: string;
  workingDirectory: string;
  execStart: string;
  port: number;
  user?: string;
}): string {
  const user = opts.user ?? "dev";
  return `[Unit]
Description=${opts.appName} Node.js application
After=network.target

[Service]
Type=simple
User=${user}
WorkingDirectory=${opts.workingDirectory}
ExecStart=${opts.execStart}
Restart=on-failure
RestartSec=5
Environment=NODE_ENV=production
Environment=PORT=${opts.port}
# Security hardening
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
`;
}

/** Caddyfile reverse-proxying a Node app with automatic HTTPS. */
export function generateCaddyfile(domain: string, upstreamPort: number): string {
  return `${domain} {
    reverse_proxy localhost:${upstreamPort}
    encode gzip

    header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains"
        X-Content-Type-Options nosniff
        X-Frame-Options DENY
        Referrer-Policy strict-origin-when-cross-origin
    }

    log {
        output file /var/log/caddy/${domain.replace(/[^a-z0-9.-]/gi, "_")}.log
    }
}
`;
}

/** Vercel CLI deploy script (Next.js + managed Neon Postgres pattern). */
export function generateVercelScript(): string {
  return `#!/usr/bin/env bash
set -euo pipefail

# Vercel deploy script — generated by ServerBuddy
echo "==> Logging in to Vercel"
vercel login

echo "==> Linking project (creates .vercel/project.json)"
vercel link

echo "==> Adding production environment variables (edit values!)"
vercel env add DATABASE_URL production
vercel env add AUTH_SECRET production

echo "==> Applying database migrations against the production DB"
npx prisma migrate deploy

echo "==> Deploying to production"
vercel --prod

echo "Done. 'vercel logs --prod' to stream runtime logs."
`;
}

/** Railway deploy script. */
export function generateRailwayScript(): string {
  return `#!/usr/bin/env bash
set -euo pipefail

# Railway deploy script — generated by ServerBuddy
echo "==> Install CLI once: npm i -g @railway/cli"
railway login

echo "==> Initialize + link project"
railway init

echo "==> Provision Postgres (creates DATABASE_URL automatically)"
railway add --database postgres

echo "==> Set app secrets"
railway variables --set "AUTH_SECRET=change-me"

echo "==> Deploy the current directory"
railway up

echo "Useful: railway logs, railway status, railway domain"
`;
}

// ---------------------------------------------------------------------
// Runbooks
// ---------------------------------------------------------------------

const VERCEL: Runbook = {
  id: "vercel",
  platform: "Vercel",
  emoji: "▲",
  blurb: "The fastest path for Next.js apps — this very project deploys this way. Build pipeline, edge network and preview URLs included.",
  requires: "A GitHub repo with a Next.js app, a database URL (e.g. Neon Postgres), a Vercel account",
  steps: [
    {
      id: "v1",
      title: "Push your app to GitHub",
      body: "Vercel builds from a Git repo. Every push to main ships to production after this setup; pull requests get their own preview URLs.",
      code: "git init\ngit add -A\ngit commit -m \"initial commit\"\ngit remote add origin git@github.com:you/your-app.git\ngit push -u origin main",
      codeLabel: "bash",
    },
    {
      id: "v2",
      title: "Import the repo on Vercel",
      body: "In the Vercel dashboard: Add New → Project → pick your repo. Vercel auto-detects Next.js (build command `next build`, output handled for you). For self-hosted Node servers you would configure the framework manually — not needed here.",
    },
    {
      id: "v3",
      title: "Set environment variables",
      body: "Add DATABASE_URL, AUTH_SECRET and any third-party keys under Settings → Environment Variables. Never commit secrets to Git — rotate any that ever leak (this project learned that lesson the hard way).",
    },
    {
      id: "v4",
      title: "Apply database migrations",
      body: "Before the first deploy, baseline your production database so `prisma migrate deploy` works. Locally you develop with `prisma db push`; production takes migrations only.",
      code: "npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script > prisma/migrations/0_init/migration.sql\nnpx prisma migrate resolve --applied 0_init\nnpx prisma migrate deploy",
      codeLabel: "bash",
    },
    {
      id: "v5",
      title: "Deploy and verify",
      body: "Deploys run automatically on push. Watch the build logs; then check /api/health-style routes and the homepage. `vercel logs --prod` streams runtime logs.",
      generates: { path: "deploy-vercel.sh", content: generateVercelScript() },
    },
  ],
  quiz: [
    {
      question: "Why must DATABASE_URL be set as an environment variable on Vercel rather than in .env committed to the repo?",
      options: [
        "Vercel cannot read .env files at all",
        "Committed secrets leak to everyone with repo access and .env is for local dev only",
        "Environment variables make the build faster",
        "It is only needed for databases",
      ],
      correctIndex: 1,
      explanation: "Anything committed to Git is in history forever. Environment variables keep secrets per-environment and out of the repo.",
    },
    {
      question: "What does `prisma migrate deploy` do differently from `prisma db push`?",
      options: [
        "It is faster",
        "It applies committed migration files in order — the auditable, production-safe path",
        "It drops the database first",
        "It generates the Prisma client",
      ],
      correctIndex: 1,
      explanation: "`db push` syncs the schema without a migration history (fine for throwaway dev). `migrate deploy` replays versioned migrations — reproducible and reviewable.",
    },
  ],
};

const RAILWAY: Runbook = {
  id: "railway",
  platform: "Railway",
  emoji: "🚄",
  blurb: "Container-based hosting with one-command Postgres provisioning. A nice middle ground between PaaS magic and raw VPS work.",
  requires: "A Node app that listens on PORT, the Railway CLI (npm i -g @railway/cli)",
  steps: [
    {
      id: "r1",
      title: "Install the CLI and log in",
      body: "Railway deploys from your machine or from GitHub. The CLI path teaches what the dashboard automates.",
      code: "npm i -g @railway/cli\nrailway login",
      codeLabel: "bash",
    },
    {
      id: "r2",
      title: "Initialize the project",
      body: "`railway init` creates a project and links the current directory. Check `railway status` to confirm the link.",
      code: "railway init\nrailway status",
      codeLabel: "bash",
    },
    {
      id: "r3",
      title: "Provision Postgres",
      body: "`railway add --database postgres` creates a database instance and injects DATABASE_URL into your service automatically — no manual wiring.",
      code: "railway add --database postgres",
      codeLabel: "bash",
    },
    {
      id: "r4",
      title: "Deploy",
      body: "`railway up` streams the build, then deploys. Get a public URL with `railway domain`. Logs: `railway logs`.",
      generates: { path: "deploy-railway.sh", content: generateRailwayScript() },
    },
  ],
  quiz: [
    {
      question: "Your app must read which variable to pick its listen port on Railway?",
      options: ["PORT", "RAILWAY_PORT", "HTTP_PORT", "It always uses 3000"],
      correctIndex: 0,
      explanation: "Railway injects PORT; apps that hard-code 3000 in production break when the platform expects PORT.",
    },
    {
      question: "What does `railway add --database postgres` give you?",
      options: [
        "A local Postgres install",
        "A managed Postgres instance with DATABASE_URL injected into the service",
        "Just a connection string to paste manually",
        "A backup of your current database",
      ],
      correctIndex: 1,
      explanation: "The database runs as another service in the project and the connection string is wired into your app's environment automatically.",
    },
  ],
};

const VPS_CADDY: Runbook = {
  id: "vps-caddy",
  platform: "VPS + Caddy",
  emoji: "🖧",
  blurb: "The full sysadmin path: raw Ubuntu VPS, systemd unit, Caddy reverse proxy with automatic HTTPS. Mirrors this project's own Caddyfile.",
  requires: "An Ubuntu 24.04 VPS with SSH access, a domain name pointed at the server, a Node app",
  steps: [
    {
      id: "s1",
      title: "Harden SSH and create a deploy user",
      body: "Log in as root once: create a limited user, give it sudo, then disable root SSH logins. Small steps, big security win.",
      code: "adduser dev\nusermod -aG sudo dev\n# then in /etc/ssh/sshd_config: PermitRootLogin no\nsystemctl restart ssh",
      codeLabel: "bash (on the VPS)",
    },
    {
      id: "s2",
      title: "Install Node + the app",
      body: "Install Node via nvm or nodesource, clone the repo, install dependencies and build. Run the app once by hand to smoke-test it.",
      code: "curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -\nsudo apt install -y nodejs\ngit clone git@github.com:you/your-app.git && cd your-app\nnpm ci && npm run build\nPORT=3000 node server.js   # smoke test, then Ctrl+C",
      codeLabel: "bash (on the VPS)",
    },
    {
      id: "s3",
      title: "Create the systemd service",
      body: "A systemd unit keeps the app alive across crashes and reboots. `systemctl enable` hooks it into boot; `journalctl -u app -f` follows its logs.",
      code: "sudo systemctl daemon-reload\nsudo systemctl enable --now app\nsystemctl status app\njournalctl -u app -n 50",
      codeLabel: "bash (on the VPS)",
      generates: {
        path: "app.service",
        content: generateSystemdUnit({
          appName: "my-app",
          workingDirectory: "/home/dev/your-app",
          execStart: "/usr/bin/node server.js",
          port: 3000,
        }),
      },
    },
    {
      id: "s4",
      title: "Install Caddy and reverse-proxy",
      body: "Caddy gives you automatic HTTPS from Let's Encrypt with zero config renewal. Point your domain's A record at the server IP first.",
      code: "sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https curl\ncurl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg\nsudo apt update && sudo apt install caddy\nsudo systemctl reload caddy",
      codeLabel: "bash (on the VPS)",
      generates: {
        path: "Caddyfile",
        content: generateCaddyfile("app.example.com", 3000),
      },
    },
    {
      id: "s5",
      title: "Verify + update flow",
      body: "Check `curl -I https://app.example.com` for a 200 and a valid TLS cert. Future updates: git pull, build, `sudo systemctl restart app` — zero-downtime comes later with a blue/green setup.",
    },
  ],
  quiz: [
    {
      question: "What does `systemctl enable --now app` do?",
      options: [
        "Starts the service once",
        "Enables it at boot AND starts it immediately",
        "Reloads the unit file",
        "Prints the service status",
      ],
      correctIndex: 1,
      explanation: "`enable` wires the unit into boot targets, `--now` also starts it right away — one command instead of two.",
    },
    {
      question: "Why does Caddy issue TLS certificates without manual steps?",
      options: [
        "It ships with a built-in certificate for *.caddy.dev",
        "It runs an ACME client (Let's Encrypt/ZeroSSL) keyed to the domain in your Caddyfile, and renews automatically",
        "TLS is only needed for banks",
        "It copies certificates from nginx",
      ],
      correctIndex: 1,
      explanation: "Caddy is an ACME client: it proves domain ownership, fetches a certificate and renews it before expiry — as long as DNS points at the server.",
    },
    {
      question: "After editing app.service, which command makes systemd re-read unit files?",
      options: ["systemctl restart app", "systemctl daemon-reload", "systemctl reload app", "Nothing — units are read live"],
      correctIndex: 1,
      explanation: "`daemon-reload` re-reads unit files; without it, your edits silently do nothing until the next reboot.",
    },
  ],
};

export const RUNBOOKS: Runbook[] = [VERCEL, RAILWAY, VPS_CADDY];

export function getRunbook(id: string): Runbook | undefined {
  return RUNBOOKS.find((r) => r.id === id);
}

/** Check quiz answers; returns the count correct + per-question verdicts. */
export function gradeQuiz(
  runbook: Runbook,
  answers: number[]
): { passed: boolean; correct: number; total: number; perQuestion: boolean[] } {
  const perQuestion = runbook.quiz.map((q, i) => answers[i] === q.correctIndex);
  const correct = perQuestion.filter(Boolean).length;
  return { passed: correct === runbook.quiz.length, correct, total: runbook.quiz.length, perQuestion };
}
