/**
 * Server-side PDF text extraction.
 *
 * HISTORY:
 *   pdf-parse@2.x changed its API from a default function export
 *   (v1: `pdfParse(buffer)` → `{ numpages, text }`) to a class
 *   (v2: `new PDFParse(uint8array, opts).getText()` → `{ pages, text, total }`).
 *   The v2 class also requires a `Uint8Array` (not a `Buffer`) and pdfjs-dist
 *   throws "Please provide binary data as Uint8Array" if you pass Buffer.
 *
 *   This silently broke ALL PDF uploads after the package was upgraded —
 *   the previous code's catch block swallowed the error and the caller
 *   returned "Could not extract enough text" for every PDF. Fixed in Phase 7.
 *
 *   Phase 7 follow-up: added standardFontDataUrl + cMapUrl so PDFs with
 *   non-Latin fonts (CJK, Arabic, Cyrillic) and PDFs that use non-embedded
 *   standard fonts (Helvetica-Bold-Italic etc.) extract correctly. Without
 *   these, pdfjs logs a warning AND may return empty text for glyphs it
 *   can't resolve — which manifested as "Could not extract enough text"
 *   for legitimate PDFs that worked in v1.
 *
 * @param buffer — PDF file contents (Node Buffer or ArrayBuffer)
 * @returns plain text extracted from the PDF (truncated to 30k chars)
 * @throws if the PDF is corrupted, password-protected, or unsupported
 */
import path from "node:path";

export async function extractPdfText(buffer: Buffer | ArrayBuffer): Promise<string> {
  // Dynamic import — pdf-parse is ESM-only in v2 and bundlers choke on it
  // if it's statically imported.
  const pdfParseModule: any = await import("pdf-parse");

  // v2 API: PDFParse is a named class export.
  // (v1 had a default function export — different API entirely.)
  const PDFParse = pdfParseModule.PDFParse ?? pdfParseModule.default;
  if (!PDFParse) {
    throw new Error("pdf-parse did not export PDFParse — package may have been downgraded.");
  }

  // v2 REQUIRES Uint8Array, not Buffer. pdfjs-dist (which pdf-parse v2 wraps)
  // explicitly throws: "Please provide binary data as Uint8Array, rather than Buffer."
  const uint8 =
    buffer instanceof Uint8Array ? buffer :
    buffer instanceof ArrayBuffer ? new Uint8Array(buffer) :
    new Uint8Array(buffer); // Node Buffer is a Uint8Array subclass — copy to be safe

  // Resolve the standard fonts + cmaps directories from pdfjs-dist.
  // These ship with the package (node_modules/pdfjs-dist/standard_fonts/
  // and node_modules/pdfjs-dist/cmaps/). Without them, pdfjs logs a
  // warning AND may return empty text for PDFs that reference non-embedded
  // standard fonts (very common for PDFs generated by Word, LibreOffice,
  // Google Docs — they all use Helvetica/Times/Courier without embedding).
  // In production (Vercel), these directories are bundled with the lambda
  // because pdfjs-dist is a dependency. In dev, they live in node_modules.
  let standardFontDataUrl: string | undefined;
  let cMapUrl: string | undefined;
  try {
    const pdfjsDistPath = require.resolve("pdfjs-dist/package.json");
    const pdfjsDistDir = path.dirname(pdfjsDistPath);
    standardFontDataUrl = path.join(pdfjsDistDir, "standard_fonts") + path.sep;
    cMapUrl = path.join(pdfjsDistDir, "cmaps") + path.sep;
  } catch {
    // If require.resolve fails (unlikely — pdfjs-dist is a transitive dep
    // of pdf-parse), fall back to no font/cmap URLs. pdfjs will log a
    // warning but should still extract Latin text.
  }

  // Cap at 30 pages to bound runtime. The caller already caps the file
  // upload size; this is a defence-in-depth against malicious PDFs with
  // thousands of empty pages.
  const instance = new PDFParse(uint8, {
    max: 30,
    // Pass font + cmap URLs so pdfjs can resolve non-embedded standard
    // fonts + CJK/Arabic/Cyrillic character maps. Without these, pdfjs
    // returns empty text for affected glyphs.
    ...(standardFontDataUrl ? { standardFontDataUrl } : {}),
    ...(cMapUrl ? { cMapUrl, cMapPacked: true } : {}),
  });

  const data = await instance.getText();

  // v2 return shape: { pages: Array<{text, num}>, text: string, total: number }
  // v1 used: { numpages: number, text: string }
  // Prefer the concatenated `text` field (which exists on both shapes);
  // fall back to joining pages[].text if the top-level text is missing.
  const text: string =
    typeof data?.text === "string" ? data.text :
    Array.isArray(data?.pages) ? data.pages.map((p: any) => p?.text ?? "").join("\n\n") :
    "";

  return text.slice(0, 30_000).trim();
}
