import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { callAI, type ChatMessage } from "@/lib/ai";

export const runtime = "nodejs";
export const maxDuration = 60;

/**
 * POST /api/study-sets/from-concept-map
 *
 * Body: {
 *   title?: string,           // optional study set title (defaults to "Concept Map: <topic>")
 *   conceptMapSpec: any,     // the concept map JSON spec (from the AI tutor chat)
 * }
 *
 * Generates a study set of flashcards directly from the concept map's nodes.
 * For each node, creates a flashcard:
 *   front: "What is <node.label>?"
 *   back: generated by AI based on the concept map context
 *
 * Also generates a few MCQ cards based on the relationships in the concept map.
 *
 * Returns { studySet: <full set with cards> }
 */
export async function POST(req: NextRequest) {
  const user = await getCurrentUser();
  const body = await req.json().catch(() => ({}));
  const title: string = (body?.title ?? "").toString().trim();
  const spec: any = body?.conceptMapSpec;

  if (!spec || typeof spec !== "object") {
    return NextResponse.json({ error: "conceptMapSpec is required" }, { status: 400 });
  }

  const nodes: Array<{ id: string; label: string; color?: string }> = Array.isArray(spec.nodes) ? spec.nodes : [];
  const edges: Array<{ from: string; to: string; label?: string }> = Array.isArray(spec.edges) ? spec.edges : [];

  if (nodes.length === 0) {
    return NextResponse.json({ error: "Concept map has no nodes" }, { status: 422 });
  }

  // Use the title field of the spec OR the central node label as the topic
  const topicName: string = (spec.title ?? "Concept Map").toString().replace(/^Concept Map:\s*/, "");
  const studySetTitle = title || `Flashcards: ${topicName}`;

  // Build an AI prompt to generate flashcard backs from the concept map structure
  const conceptMapText = `
Topic: ${topicName}
Nodes: ${nodes.map((n) => n.label).join(", ")}
Relationships:
${edges.map((e) => {
  const fromLabel = nodes.find((n) => n.id === e.from)?.label ?? e.from;
  const toLabel = nodes.find((n) => n.id === e.to)?.label ?? e.to;
  return `  - ${fromLabel} --(${e.label ?? "related to"})--> ${toLabel}`;
}).join("\n")}
`.trim();

  const systemPrompt = `You are an educational flashcard generator. The user has built a concept map and wants flashcards based on it.

CONCEPT MAP:
${conceptMapText}

For EACH node in the concept map, generate a flashcard with:
- front: "What is <node label>?"
- back: A clear, concise definition or explanation of the concept (1-2 sentences, max 50 words), suitable for a student. The explanation should reference related nodes in the concept map when relevant (e.g. "is related to", "is part of", "is connected to").

Also generate 3 multiple-choice questions (MCQs) based on the concept map relationships:
- question: a question testing the relationships (e.g. "What is <X> connected to?")
- options: 4 options (one correct, three distractors using other node labels)
- correctIndex: 0-3 (index of the correct answer)
- explanation: a brief explanation of why the answer is correct

Return ONLY valid JSON:
{
  "flashcards": [{"front": "...", "back": "..."}],
  "mcqs": [{"question": "...", "options": ["A","B","C","D"], "correctIndex": 0, "explanation": "..."}]
}`;

  let flashcards: Array<{ front: string; back: string }> = [];
  let mcqs: Array<{ question: string; options: string[]; correctIndex: number; explanation: string }> = [];

  try {
    const messages: ChatMessage[] = [
      { role: "system", content: systemPrompt },
      { role: "user", content: "Generate the flashcards and MCQs from this concept map." },
    ];
    const reply = await callAI(messages, null, {
      userId: user.id,
      route: "/api/study-sets/from-concept-map",
    });

    let cleaned = reply.trim();
    if (cleaned.startsWith("```")) {
      cleaned = cleaned.replace(/^```(?:json)?\s*/i, "").replace(/```\s*$/i, "");
    }
    const firstBrace = cleaned.indexOf("{");
    const lastBrace = cleaned.lastIndexOf("}");
    if (firstBrace !== -1 && lastBrace !== -1) {
      const parsed = JSON.parse(cleaned.slice(firstBrace, lastBrace + 1));
      flashcards = parsed.flashcards ?? [];
      mcqs = parsed.mcqs ?? [];
    }
  } catch (e: any) {
    console.error("[from-concept-map] AI generation failed:", e?.message);
    // Fall back to simple flashcards from node labels
    flashcards = nodes.map((n) => ({
      front: `What is ${n.label}?`,
      back: `A concept related to ${topicName}.`,
    }));
  }

  // Create the study set + cards in the database
  const studySet = await db.studySet.create({
    data: {
      userId: user.id,
      title: studySetTitle,
      sourceType: "text",
      sourceText: conceptMapText,
      subject: topicName,
      topic: topicName,
    },
  });

  // Insert flashcards
  for (const fc of flashcards) {
    await db.card.create({
      data: {
        setId: studySet.id,
        cardType: "flashcard",
        front: fc.front,
        back: fc.back,
        subject: topicName,
        topic: topicName,
      },
    });
  }

  // Insert MCQs
  for (const mcq of mcqs) {
    await db.card.create({
      data: {
        setId: studySet.id,
        cardType: "mcq",
        question: mcq.question,
        options: mcq.options,
        correctIndex: mcq.correctIndex,
        explanation: mcq.explanation,
        subject: topicName,
        topic: topicName,
      },
    });
  }

  const withCards = await db.studySet.findUnique({
    where: { id: studySet.id },
    include: { cards: { orderBy: { createdAt: "asc" } } },
  });

  return NextResponse.json({
    studySet: withCards,
    flashcardCount: flashcards.length,
    mcqCount: mcqs.length,
  });
}
