/**
 * Tutor Plugin Types — Phase AC2
 *
 * Foundation type system for the invisible plugin architecture.
 *
 * DESIGN PRINCIPLES (from advisor):
 *   1. Learner never sees plugin IDs, schemas, or routing internals
 *   2. The AI cannot provide a module path, package name, JS, remote URL, or
 *      React component — only developer-approved plugins in the registry
 *   3. Deterministic routing wins over AI selection when possible
 *   4. Workspace context (active artifact) wins over re-routing on follow-ups
 *   5. Every plugin call returns ONE of four ToolResult variants:
 *      ready | clarification_required | unsupported | failed
 *   6. The tutor only says "ready" if the plugin returned status: "ready"
 *
 * This module is pure types — no behavior, no I/O. Phase AC3 will wire it in.
 *
 * NOT WIRED INTO CHAT FLOW YET — see TUTOR_PLUGIN_FRAMEWORK_ENABLED flag.
 */

// ============================================================
// Categories — top-level tool families
// ============================================================

export type ToolCategory =
  | "graph"
  | "diagram"
  | "code"
  | "assessment"
  | "simulation"
  | "writing"
  | "drawing";

// ============================================================
// Actions — what the learner wants to do
// ============================================================

export type ActionVerb =
  | "create" // make a new artifact
  | "modify" // change an existing artifact
  | "inspect" // examine / explain an existing artifact
  | "run" // execute code or run a simulation
  | "review"; // assess an answer or submit work

// ============================================================
// Manifest — every plugin advertises its abilities
// ============================================================

export type LearningToolCapabilities = {
  render: boolean; // can it display in the workspace?
  edit: boolean; // can the learner modify the artifact?
  execute: boolean; // can it run code or simulate?
  save: boolean; // can the result be saved as a Project?
  offline: boolean; // does it work without a network?
};

export type LearningToolManifest = {
  /** Stable internal ID, e.g. "graph.bar". NEVER shown to the learner. */
  id: string;
  /** Schema version of the manifest itself. Bump when adding fields. */
  version: number;
  /** Top-level category for hierarchical routing. */
  category: ToolCategory;
  /** What this plugin can do. The router rejects requests for unsupported actions. */
  supportedActions: ActionVerb[];
  /** Capabilities advertised to the workspace + router. */
  capabilities: LearningToolCapabilities;
  /** Free-text search terms for AI-assisted routing (last resort only). */
  searchTerms: string[];
  /** Required input fields the plugin understands (free-form list — validated by the adapter). */
  inputRequirements: string[];
  /** Availability — disabled plugins are filtered out of routing. */
  availability: {
    enabled: boolean;
    supportedPlatforms: Array<"web" | "mobile">;
  };
};

// ============================================================
// Constraint Envelope — per-request constraints
// ============================================================

/**
 * Built by TutorActionController from the learner's message + intents + active
 * workspace. Constrains what the router is allowed to pick.
 *
 * Example: { action: "create", category: "graph", requestedType: "bar",
 *            allowedPlugins: ["graph.bar"], maximumPrimaryArtifacts: 1 }
 */
export type ConstraintEnvelope = {
  action: ActionVerb;
  category: ToolCategory | null;
  /** Specific subtype the learner asked for (e.g. "bar", "pie", "flowchart"). */
  requestedType: string | null;
  /** Whitelist of plugin IDs the router may pick from. */
  allowedPlugins: string[];
  /** Hard cap on primary artifacts (default 1). Secondary attachments (source/video/image) are exempt. */
  maximumPrimaryArtifacts: number;
};

// ============================================================
// Workspace Artifact — the common wrapper every plugin returns
// ============================================================

export type WorkspaceArtifact = {
  /** Stable UUID generated by the plugin or controller. */
  artifactId: string;
  /** Which plugin produced this artifact. Used by the workspace to load the right renderer. */
  plugin: {
    id: string;
    version: number;
  };
  /** Schema version of the artifact payload itself. */
  artifactVersion: number;
  /** Human-readable title shown in the workspace header. */
  title: string;
  /** Lifecycle state. */
  status: "draft" | "ready" | "submitted" | "completed";
  /** Where this artifact came from. */
  source: {
    conversationId: string | null;
    messageId: string | null;
  };
  /** Plugin-specific payload. The workspace uses plugin.id to pick the renderer. */
  payload: unknown;
};

// ============================================================
// Tool Result — the only four ways a plugin call can end
// ============================================================

export type ToolSummary = {
  /** One-line learner-facing message. NEVER exposes plugin IDs or routing internals. */
  shortMessage: string;
  /** Optional longer explanation the tutor can use. */
  detail?: string;
};

export type ToolResult =
  | {
      status: "ready";
      artifact: WorkspaceArtifact;
      tutorSummary: ToolSummary;
    }
  | {
      status: "clarification_required";
      /** Learner-facing clarifying question, e.g. "What values should I use for each bar?" */
      question: string;
    }
  | {
      status: "unsupported";
      /** Internal reason code (admin logs only). */
      reasonCode: string;
      /** Learner-facing alternative suggestions, e.g. ["Python", "JavaScript"]. */
      alternatives: string[];
    }
  | {
      status: "failed";
      /** Internal error code (admin logs only). */
      errorCode: string;
      /** Learner-facing safe message — never includes stack traces or internals. */
      safeMessage: string;
    };

// ============================================================
// Routing Decision — the controller's output to the router
// ============================================================

export type RoutingDecision = {
  /** The plugin ID chosen by the router, or null if clarification is needed. */
  pluginId: string | null;
  /** Confidence 0–1. Below the threshold, the router asks for clarification. */
  confidence: number;
  /** Which routing step produced this decision. */
  matchedStep: "deterministic" | "workspace_context" | "ai_shortlist" | "clarification";
  /** Candidate plugin IDs the router considered (for admin logs only). */
  candidatesConsidered: string[];
  /** The constraint envelope the router satisfied. */
  envelope: ConstraintEnvelope;
};

// ============================================================
// Workspace context — what the learner is currently looking at
// ============================================================

/**
 * Sent by the client as a SEPARATE field in the request body (NOT in the
 * visible message). The router uses this on follow-up turns: "change Diana
 * to 8" → modify the active graph.bar artifact, don't search for a new plugin.
 */
export type WorkspaceContext = {
  artifactType: string;
  artifactId: string | null;
  artifactCaption: string;
  /** Snapshot of the artifact's payload (bounded to 800 chars by the controller). */
  payloadSummary: string;
};

// ============================================================
// Helpers
// ============================================================

export function isReady(result: ToolResult): result is Extract<ToolResult, { status: "ready" }> {
  return result.status === "ready";
}

export function isClarification(
  result: ToolResult,
): result is Extract<ToolResult, { status: "clarification_required" }> {
  return result.status === "clarification_required";
}

export function isUnsupported(
  result: ToolResult,
): result is Extract<ToolResult, { status: "unsupported" }> {
  return result.status === "unsupported";
}

export function isFailed(result: ToolResult): result is Extract<ToolResult, { status: "failed" }> {
  return result.status === "failed";
}

// ============================================================
// Learner-facing status strings (used by the client during routing)
// ============================================================

/** Status messages shown to the learner. NEVER mention plugin IDs, schemas, or internals. */
export const LEARNER_STATUS = {
  understanding: "Understanding your request…",
  preparingGraph: "Preparing your graph…",
  preparingFlowchart: "Preparing your flowchart…",
  preparingCode: "Preparing your code…",
  preparingQuiz: "Preparing your quiz…",
  ready: "Your activity is ready.",
  openWorkspace: "Open workspace",
  clarificationDefault: "Could you tell me a bit more about what you'd like?",
  unsupportedDefault:
    "I can't do that yet. Let me know if you'd like to try a different activity instead.",
  failedDefault:
    "Something went wrong preparing that. Please try again, or ask me a different way.",
} as const;
